version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: uv
    directory: /dns
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: uv
    directory: /ansible
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
