#!/usr/bin/env python3
import argparse
import base64
import http.client
import json
import re
import sys
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

SOURCES = {
    "chromium": "https://chromium.googlesource.com/chromium/src/+/main/services/network/public/cpp/permissions_policy/permissions_policy_features.json5?format=TEXT",
    "firefox": "https://raw.githubusercontent.com/mozilla-firefox/firefox/main/dom/security/featurepolicy/FeaturePolicyUtils.cpp",
    "webkit": "https://raw.githubusercontent.com/WebKit/WebKit/main/Source/WebCore/html/PermissionsPolicy.cpp",
    "w3c": "https://raw.githubusercontent.com/w3c/webappsec-permissions-policy/main/features.md",
}

# Features gated on this runtime flag exist only for Chromium's own origin trial tests.
TEST_ONLY_FLAG = "OriginTrialsSampleAPI"

# Upstream file moves and format changes would otherwise drain a source silently.
MIN_COUNTS = {"chromium": 90, "firefox": 20, "webkit": 15, "w3c": 70}

TIMEOUT = 30

REPO = Path(__file__).resolve().parent.parent
LOCK_RELATIVE = "ansible/roles/caddy/vars/main/permissions_policy.yml"
LOCK_PATH = REPO / LOCK_RELATIVE

LOCK_HEADER = """---
# Generated by python3 scripts/permissions_policy_features.py --write. Do not edit.
caddy_permissions_policy: >-
"""

LOCKED_BLOCK = re.compile(
    r"^caddy_permissions_policy: >-\n((?:[ \t]+\S.*\n)+)", re.MULTILINE
)
LOCKED_DIRECTIVE = re.compile(r"([a-z0-9-]+)=\(\)")


def fetch_text(url):
    with urllib.request.urlopen(url, timeout=TIMEOUT) as response:
        body = response.read()
    if url.endswith("format=TEXT"):
        return base64.b64decode(body).decode()
    return body.decode()


def parse_chromium(text):
    data = text.partition("data: [")[2]
    out = {}
    for block in re.findall(r"\{[^{}]*\}", data):
        name = re.search(r'permissions_policy_name:\s*"([^"]+)"', block)
        if not name:
            continue
        field = re.search(r"depends_on:\s*\[([^\]]*)\]", block)
        depends_on = re.findall(r'"([^"]+)"', field.group(1) if field else "")
        if TEST_ONLY_FLAG in depends_on:
            continue
        out[name.group(1)] = {
            "isolated_context_only": bool(
                re.search(r'visibility:\s*"IsolatedContext"', block)
            ),
            "depends_on": depends_on,
        }
    return out


def parse_firefox(text):
    out = {}
    for array in ("sSupportedFeatures", "sExperimentalFeatures"):
        body = text.partition(f"{array}[] = {{")[2].partition("};")[0]
        for name in re.findall(r'\{\s*"([^"]+)"', body):
            out[name] = {"experimental": array == "sExperimentalFeatures"}
    return out


def parse_webkit(text):
    names = re.findall(r'constexpr auto \w+Token \{ "([^"]+)"_s \}', text)
    return {name: {} for name in names}


def parse_w3c(text):
    out = {}
    section = ""
    for line in text.split("\n"):
        heading = re.match(r"##\s+(.*)", line)
        if heading:
            section = heading.group(1).strip()
        cell = re.match(r"\|\s*`([a-z0-9-]+)`\s*\|", line)
        if cell:
            out[cell.group(1)] = {"section": section}
    return out


PARSERS = {
    "chromium": parse_chromium,
    "firefox": parse_firefox,
    "webkit": parse_webkit,
    "w3c": parse_w3c,
}


def fail(message):
    print(f"FAIL: {message}", file=sys.stderr)
    return 2


# A folded scalar keeps one directive per line, so a new feature is a one-line diff.
def render_lock(names):
    return LOCK_HEADER + ",\n".join(f"  {n}=()" for n in names) + "\n"


def read_locked():
    try:
        text = LOCK_PATH.read_text()
    except OSError:
        return None
    block = LOCKED_BLOCK.search(text)
    if not block:
        raise SystemExit(
            fail(f"{LOCK_RELATIVE} has no caddy_permissions_policy folded scalar.")
        )
    return LOCKED_DIRECTIVE.findall(block.group(1))


def collect():
    with ThreadPoolExecutor(max_workers=len(SOURCES)) as pool:
        texts = list(pool.map(fetch_text, SOURCES.values()))
    return {
        source: PARSERS[source](text)
        for source, text in zip(SOURCES, texts, strict=True)
    }


def merge(parsed):
    features = {}
    for source, names in parsed.items():
        for name, meta in names.items():
            feature = features.setdefault(
                name, {"name": name, "sources": [], "meta": {}}
            )
            feature["sources"].append(source)
            feature["meta"][source] = meta
    return [features[name] for name in sorted(features)]


def main():
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()

    try:
        parsed = collect()
    except (OSError, http.client.HTTPException, ValueError) as error:
        return fail(f"cannot read upstream sources: {error}")

    for source, names in parsed.items():
        if len(names) < MIN_COUNTS[source]:
            return fail(
                f"{source} yielded {len(names)} features, expected >= "
                f"{MIN_COUNTS[source]}. Parser is likely broken."
            )

    selected = merge(parsed)

    if not args.check and not args.write:
        print(
            json.dumps(
                {
                    "generated_from": SOURCES,
                    "counts": {s: len(n) for s, n in parsed.items()},
                    "total": len(selected),
                    "features": selected,
                },
                indent=2,
            )
        )
        return 0

    upstream = [feature["name"] for feature in selected]
    locked = read_locked()
    if locked is None and args.check:
        return fail(f"cannot read {LOCK_RELATIVE}")
    added = [n for n in upstream if n not in (locked or [])]
    gone = [n for n in (locked or []) if n not in upstream]

    if args.write:
        merged = sorted(set((locked or []) + upstream))
        LOCK_PATH.write_text(render_lock(merged))
        print(f"wrote {len(merged)} features to {LOCK_RELATIVE}")
        if locked is None:
            print("  created from scratch")
        else:
            print(f"  added: {' '.join(added) if added else 'none'}")
        if gone:
            print(f"  kept, no longer upstream: {' '.join(gone)}")
        return 0

    print(f"locked {len(locked)} / upstream {len(upstream)}")
    if gone:
        print(
            "  dropped upstream (kept, unknown directives are ignored): "
            f"{' '.join(gone)}"
        )
    if not added:
        print("  no new features")
        return 0
    print(f"  NEW upstream features missing from {LOCK_RELATIVE}, run --write:")
    for name in added:
        print(f"  - {name}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
