name: Ansible

on:
  pull_request:
    paths:
      - ansible/**
      - .github/workflows/ansible.yml
  push:
    branches:
      - main
    paths:
      - ansible/**
      - .github/workflows/ansible.yml

defaults:
  run:
    working-directory: ansible

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
      - run: uv sync --locked
      - run: uv run ansible-galaxy collection install -r requirements.yml
      - run: uv run ansible-playbook mail.yml --syntax-check
      - run: uv run ansible-lint
