name: Mail

on:
  pull_request:
    paths:
      - mail/**
      - roles/**
      - .github/workflows/mail.yml
  push:
    branches:
      - main
    paths:
      - mail/**
      - roles/**
      - .github/workflows/mail.yml

defaults:
  run:
    working-directory: mail

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
      - run: uv sync --locked
      - run: uv run ansible-galaxy collection install -r requirements.yml
      - run: uv run ansible-playbook site.yml --syntax-check
      - run: uv run ansible-lint . ../roles
