AllowAgentForwarding no
AuthenticationMethods publickey
KbdInteractiveAuthentication no
MaxAuthTries 3
PasswordAuthentication no
PermitEmptyPasswords no
PermitRootLogin no
PubkeyAuthentication yes
X11Forwarding no
